name: Deploy Portfolio to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::253918336037:role/GitHubActions-AWS-Cloud-Portfolio
          aws-region: eu-west-2

      - name: Deploy website to S3
        run: |
          aws s3 sync . s3://matthew-aws-cloud-portfolio \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md"

      - name: Refresh CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1YVN95C4H7HP1 \
            --paths "/*"

      - name: Show GitHub OIDC subject
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            const payload = JSON.parse(
              Buffer.from(token.split('.')[1], 'base64url').toString()
            );
            console.log("OIDC subject:", payload.sub);
